ase1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from registration import views as jk
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('dashboard/', include(('dashboard.urls', 'dashboard'))),
                  path('registration/', include('registration.urls')),
                  path('', include(('landing_page.urls', 'landing_page'))),
                  path('student_report/', include(('student_report.urls','student_report'))),
                  url(r'auth/', include(('social_django.urls', 'social'))),
                  path('api/<str:course_id>',jk.courselogdetail,name='api')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
from registration import views as p

app_name = "dashboard"

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('needy_list/', views.needy_list, name='needy_list'),
    path('list_of_students/', views.list_of_students, name='list_of_students'),
    path('editprofile/', p.editprofile, name='editprofile'),
    path('custom_404/', views.custom_404, name='custom_404'),
    path('graph', views.graph, name='graph'),
]

registration/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
import social_django
app_name = "registration"

urlpatterns = [
    path('login/', views.login_display, name='login'),
    path('register/', views.register_display, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/reset_password/', views.reset_password, name='reset'),
    url(r'display_reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.display_reset_password, name='display_reset_password'),
    path('course/', views.course_selection, name='course_selection'),
    url(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.activate, name='activate'),
    path('save_password/',views.save_password,name='save_password'),
    path('edit_profile/',views.editprofile,name='edit_profile'),
    path('all_profiles/',views.allprofiles,name='allprofiles'),
    path('professor/',views.professor,name='professor')
    ]

student_report/urls.py
from django.urls import path
from . import views

app_name = 'student_report'

urlpatterns = [
    path('<int:id>/', views.student_report, name="student_report"),
    path('charts/<int:id>/', views.charts, name="charts"),
    path('tables/<int:id>/', views.tables, name="tables"),
]

student_report/models.py
from django.db import models

# Create your models here.

student_report/forms.py
from django import forms


class label_class(forms.Form):
    label = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Add Label'}))

student_report/views.py
from django.shortcuts import render
from dashboard.models import Marks, Enrollments, User, student_ranks, course_dashboard, course_exams
from registration.models import professor_profile
from django.shortcuts import HttpResponse
from .forms import label_class

def student_report(request, id):
    if id == 0:
        return HttpResponse('No  reports to show')
    user = User.objects.get(username=request.user)
    profile = professor_profile.objects.get(professor=user)
    if request.method=='POST':
        form = label_class(request.POST)
        if form.is_valid():
            p=Enrollments.objects.get(course_id=profile.professor_course,student_id=id)
            p.label = form.cleaned_data.get('label')
            p.save()
            form = label_class()
    else:
        form = label_class()
    student_quizzes = Marks.objects.filter(prof_id=user, course_id=profile.professor_course, student_id=id)
    quizzes = []
    average_marks = []
    quiz_marks = []
    for i in student_quizzes:
        quiz_name = i.q_name
        marks = i.marks
        quiz_students = Marks.objects.filter(course_id=profile.professor_course, prof_id=user, q_name=quiz_name)
        sum = 0
        quiz_marks.append(int(marks))
        for j in quiz_students:
            sum = sum + int(j.marks)
        average = sum / len(quiz_students)
        average_marks.append(int(average))
        quizzes.append([quiz_name, marks, average])
    maximum = max(max(quiz_marks),max(average_marks))
    name = Enrollments.objects.get(prof_id=user, course_id=profile.professor_course, student_id=id)
    rank = student_ranks.objects.get(student_id=id, course=profile.professor_course)
    ranks = [rank.class_rank, rank.exam_rank, rank.lab_rank, rank.asgn_rank, rank.oth_rank]
    student_marks = [rank.best_exam, rank.best_marks, rank.worst_exam, rank.worst_marks, rank.overall]
    label = Enrollments.objects.get(course_id=profile.professor_course,student_id=id)
    return render(request, "student_report/student_report.html",
                  {'quizzes': quizzes, 'sid': id,'form':form ,'student': name.student_name, 'ranks': ranks, 'Marks': student_marks,'Maximum':maximum,'label':label.label})




def charts(request, id):
    user = User.objects.get(username=request.user)
    profile = professor_profile.objects.get(professor=user)
    if request.method == 'POST':
        form = label_class(request.POST)
        if form.is_valid():
            p = Enrollments.objects.get(course_id=profile.professor_course, student_id=id)
            p.label = form.cleaned_data.get('label')
            p.save()
            form = label_class()
    else:
        form = label_class()
    student_quizzes = Marks.objects.filter(prof_id=user, course_id=profile.professor_course, student_id=id)
    quizzes = []
    for i in student_quizzes:
        quiz_name = i.q_name
        marks = i.marks
        quiz_students = Marks.objects.filter(course_id=profile.professor_course, prof_id=user, q_name=quiz_name)
        sum = 0
        for j in quiz_students:
            sum = sum + int(j.marks)
        average = sum / len(quiz_students)
        quizzes.append([quiz_name, marks, average])
    name = Enrollments.objects.get(prof_id=user, course_id=profile.professor_course, student_id=id)
    label = Enrollments.objects.get(course_id=profile.professor_course, student_id=id)
    return render(request, "student_report/charts.html",
                  {'quizzes': quizzes, 'sid': id, 'student': name.student_name,'form':form,'label':label.label})


def tables(request, id):
    user = User.objects.get(username=request.user)
    profile = professor_profile.objects.get(professor=user)
    if request.method == 'POST':
        form = label_class(request.POST)
        if form.is_valid():
            p = Enrollments.objects.get(course_id=profile.professor_course, student_id=id)
            p.label = form.cleaned_data.get('label')
            p.save()
            form = label_class()
    else:
        form = label_class()
    student_courses = student_ranks.objects.filter(student_id=id)
    all_course_table = []
    for i in range(len(student_courses)):
        course = student_courses[i].course
        print(course)
        c_average = course_dashboard.objects.get(course=course).course_average
        all_course_table.append(
            [student_courses[i].course, student_courses[i].overall, c_average, student_courses[i].class_rank])
    this_course_table = []
    quizzes = course_exams.objects.filter(course_id=profile.professor_course)
    for i in range(len(quizzes)):
        print(quizzes[i].quiz_name)
        exam_marks = Marks.objects.get(student_id=id, prof_id=user, course_id=profile.professor_course,
                                       q_name=quizzes[i].quiz_name)
        this_course_table.append(
            [quizzes[i].quiz_name.split('-')[1], quizzes[i].avg_marks, quizzes[i].max_marks, exam_marks.marks])
    name = Enrollments.objects.get(prof_id=user, course_id=profile.professor_course, student_id=id)
    label = Enrollments.objects.get(course_id=profile.professor_course, student_id=id)
    return render(request, "student_report/tables.html",
                  {'sid': id, 'course_table': all_course_table, 'this_course': this_course_table,
                   'student': name.student_name,'form':form,'label':label.label,'course':profile.professor_course})

student_report/templates/student_report/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "student_report/css/vendor.bundle.base.css" %}">
    <link rel="stylesheet" href="{% static "student_report/css/vendor.bundle.addons.css" %}">
    <link rel="stylesheet" href="{% static "student_report/css/style.css" %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
          integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="{% static "landing_page/css/one-page-wonder.css" %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static "landing_page/css/one-page-wonder.css" %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <style>
        * {
            font-family: 'Montserrat', sans-serif;
        }
    </style>
    {% block head %}
        {% load static %}
    {% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img class="img-responsive" src="{% static "landing_page/images/LMS.svg" %}" alt="LMS" width="50"
                 height="50" style="position:absolute;z-index:4;top:7%;left:6%;">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'landing_page:landing_page' %}">Home</a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{% url 'registration:register' %}">Sign Up</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-light" href="{% url 'registration:login' %}">Log In</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <div class="btn-group" style="border:0px;background: #231f20;">
                            <a class="nav-link text-light" href="{% url 'dashboard:dashboard' %}" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">Dashboard<i class="fas fa-caret-down"></i></a>
                            <div class="dropdown-menu" style="background: #231f20;border:0px;color:white;">
                                <a class="dropdown-item" href="{% url 'dashboard:dashboard' %}" style="color:white;">Dashboard</a>
                                <a class="dropdown-item" href="{% url 'dashboard:needy_list' %}" style="color:white;">Needy
                                    List</a>
                                <a class="dropdown-item" href="{% url 'dashboard:list_of_students' %}"
                                   style="color:white;">List of All Students</a>
                            </div>
                        </div>

                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-light" href="{% url 'registration:logout' %}">Logout</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>

<div class="container-scroller">
    <div class="container-fluid page-body-wrapper">
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
            <ul class="nav">
                <li class="nav-item nav-profile">
                    <div class="nav-link">
                        <div class="user-wrapper">

                            <a href="#" style="text-decoration: none;">
                                <img class="img-responsive rounded mx-5 mt-3 border"
                                     src="{% static 'dashboard/images/st6.jpg' %}" alt="Professor Name" width="120"
                                     height="120"/>
                                <div class="page-header mx-4 my-4 text-center">
                                    <h1 style="font-family: 'Montserrat', sans-serif;">{{ student }}</h1>
                                </div>
                            </a>

                        </div>
                    </div>
                </li>
                 <li class="nav-item text-center">
                    <span class="badge badge-primary mb-2">{{ label }}</span>
                    <div class="w-75 mx-auto form-group">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form.label }}<br/>
                            <button type="submit" class="btn btn-success">ADD</button>
                        </form>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'student_report:student_report' sid %}">
                        <i class="menu-icon mdi mdi-television"></i>
                        <span class="menu-title">Dashboard</span>
                    </a>
                </li>


                <li class="nav-item">
                    <a class="nav-link" href="{% url 'student_report:charts' sid %}">
                        <i class="menu-icon mdi mdi-chart-line"></i>
                        <span class="menu-title">Charts</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'student_report:tables' sid %}">
                        <i class="menu-icon mdi mdi-table"></i>
                        <span class="menu-title">Tables</span>
                    </a>
                </li>

            </ul>
        </nav>

        <div class="main-panel">
            <div class="content-wrapper">
                {% block content %}
                    {% load static %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>

<footer class="py-5 bg-black">
    <div class="container">
        <p class="m-0 text-center text-white small mb-2 footer_text">Copyright &copy; LMS</p>
        <p class="m-0 text-center text-white small footer_text">Made With <i class="fa fa-heart mx-1"></i>work</p>
    </div>

    <a class="scrollup" style="display: none;">Scroll</a>
    <!-- /.container -->
</footer>


<!-- plugins:js -->
<script src="{% static "student_report/js/vendor.bundle.base.js" %}"></script>
<script src="{% static "student_report/js/vendor.bundle.addons.js" %}"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="{% static "student_report/js/misc.js" %}"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="{% static "student_report/js/dashboard.js" %}"></script>
<!-- End custom js for this page-->
<script src="{% static "student_report/js/chart.js" %}"></script>
<script src="{% static 'student_report/js/Chart.bundle.js' %}"></script>
{% block script %}
{% endblock %}
</body>
</html>

student_report/templates/student_report/charts.html
{% extends 'student_report/base.html' %}

{% block head %}
    <title>Charts</title>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Line chart</h4>
                    <canvas id="myChart1" style="height:250px"></canvas>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Bar chart</h4>
                    <canvas id="myChart2" style="height:230px"></canvas>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
        var ctx = document.getElementById("myChart1").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: [{% for quiz in quizzes %}"{{ quiz.0 }}",{% endfor %}],
                datasets: [{
                    label: "{{ student }}",
                    data: [{% for quiz in quizzes %}{{ quiz.1 }}, {% endfor %}],
                    backgroundColor: "rgba(153,255,51,0.6)",
                    borderColor: "rgba(153,255,51,0.6)",
                    fill: false
                }, {
                    label: 'Average',
                    data: [{% for quiz in quizzes %}{{ quiz.2 }}, {% endfor %}],
                    backgroundColor: "rgba(255,153,0,0.6)",
                    borderColor: "rgba(255,153,0,0.6)",
                    fill: false
                }]
            }
        });

        var ctx = document.getElementById("myChart2").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: [{% for quiz in quizzes %}"{{ quiz.0 }}",{% endfor %}],
                datasets: [{
                    label: "{{ student }}",
                    data: [{% for quiz in quizzes %}{{ quiz.1 }}, {% endfor %}],
                    backgroundColor: "rgba(153,255,51,0.6)"
                }, {
                    label: 'Average',
                    data: [{% for quiz in quizzes %}{{ quiz.2 }}, {% endfor %}],
                    backgroundColor: "rgba(255,153,0,0.6)"
                }]
            }
        });

    </script>
{% endblock %}

student_report/templates/student_report/student_report.html
{% extends 'student_report/base.html' %}
{% load static %}

{% block head %}
    <title>Student Report</title>
{% endblock %}

{% block content %}
    <div class="col-4 text-left mb-4">
    <form>
        <a onclick="window.print()"><i class="fa fa-download fa-2x text-left" aria-hidden="true" data-toggle="tooltip"
           title="Download Report"></i></a>
    </form>
    </div>
    <div class="row">
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
            <div class="card card-statistics">
                <div class="card-body">
                    <div class="clearfix">
                        <div class="float-left">
                            <i class="mdi mdi-cube text-danger icon-lg"></i>
                        </div>
                        <div class="float-right">
                            <p class="mb-0 text-right">Exam Rank</p>
                            <div class="fluid-container">
                                <h3 class="d-inline-block font-weight-medium text-right mb-0" style="font-family: 'Montserrat', sans-serif;">{{ ranks.1 }}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
            <div class="card card-statistics">
                <div class="card-body">
                    <div class="clearfix">
                        <div class="float-left">
                            <i class="mdi mdi-receipt text-warning icon-lg"></i>
                        </div>
                        <div class="float-right">
                            <p class="mb-0 text-right">Lab Rank</p>
                            <div class="fluid-container">
                                <h3 class="font-weight-medium text-right mb-0" style="font-family: 'Montserrat', sans-serif;">{{ ranks.2 }}</h3>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
            <div class="card card-statistics">
                <div class="card-body">
                    <div class="clearfix">
                        <div class="float-left">
                            <i class="mdi mdi-poll-box text-success icon-lg"></i>
                        </div>
                        <div class="float-right">
                            <p class="mb-0 text-right">Assignment Rank</p>
                            <div class="fluid-container">
                                <h3 class="font-weight-medium text-right mb-0" style="font-family: 'Montserrat', sans-serif;">{{ ranks.3 }}</h3>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
            <div class="card card-statistics">
                <div class="card-body">
                    <div class="clearfix">
                        <div class="float-left">
                            <i class="mdi mdi-account-location text-info icon-lg"></i>
                        </div>
                        <div class="float-right">
                            <p class="mb-0 text-right">Other Rank</p>
                            <div class="fluid-container">
                                <h3 class="font-weight-medium text-right mb-0" style="font-family: 'Montserrat', sans-serif;">{{ ranks.4 }}</h3>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-9 grid-margin stretch-card">
            <div class="col-md-12 grid-margin">
                <div class="card">
                    <div class="card-body">
                        <div class="chart-container">
                            <canvas id="myChart" height="190"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h2 class="card-title text-primary mb-5">Performance History</h2>
                    <div class="wrapper d-flex justify-content-between">
                        <div class="side-left">
                            <p class="mb-2">Class Rank</p>
                            <p class="display-3 mb-4 font-weight-light">{{ ranks.0 }}</p>
                        </div>
                      </div>
                    <div class="wrapper d-flex justify-content-between">
                        <div class="side-left">
                            <p class="mb-2">Best performance</p>
                            <p class="display-3 mb-5 font-weight-light">{{ Marks.1 }}</p>
                        </div>
                        <div class="side-right">
                      <small class="text-muted">{{ Marks.0 }}</small>
                    </div>
                    </div>
                    <div class="wrapper d-flex justify-content-between">
                        <div class="side-left">
                            <p class="mb-2">Worst performance</p>
                            <p class="display-3 mb-5 font-weight-light">{{ Marks.3 }}</p>
                        </div>
                        <div class="side-right">
                      <small class="text-muted">{{ Marks.2 }}</small>
                    </div>
                    </div>
{#                    <div class="wrapper">#}
{#                        <div class="d-flex justify-content-between">#}
{#                            <p class="mb-2">Sales</p>#}
{#                            <p class="mb-2 text-primary">88%</p>#}
{#                        </div>#}
{#                        <div class="progress">#}
{#                            <div class="progress-bar bg-primary progress-bar-striped progress-bar-animated"#}
{#                                 role="progressbar" style="width: 88%" aria-valuenow="88"#}
{#                                 aria-valuemin="0" aria-valuemax="100"></div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="wrapper mt-4">#}
                        <div class="d-flex justify-content-between">
                            <p class="mb-2">Overall</p>
                            <p class="mb-2 text-success display-4 font-weight-bold">{{ Marks.4 }}%</p>
                        </div>
                        <div class="progress">
                            <div class="progress-bar bg-success progress-bar-striped progress-bar-animated"
                                 role="progressbar" style="width: {{ Marks.4 }}%" aria-valuenow="56"
                                 aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        var ctx = document.getElementById("myChart").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [{% for quiz in quizzes %}"{{ quiz.0 }}",{% endfor %}],
                datasets: [{
                    label: "{{ student }}",
                    data: [{% for quiz in quizzes %}{{ quiz.1 }}, {% endfor %}],
                    backgroundColor: "rgba(153,255,51,0.6)"
                }, {
                    label: 'Average',
                    data: [{% for quiz in quizzes %}{{ quiz.2 }}, {% endfor %}],
                    backgroundColor: "rgba(255,153,0,0.6)"
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true,
                            steps: 10,
                            stepValue: 5,
                            max: {{ Maximum }}
                        }
                    }]
                }
            }
        });
    </script>

{% endblock %}

student_report/templates/student_report/tables.html
{% extends 'student_report/base.html' %}

{% block head %}
    <title>Title</title>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">All Course Details</h4>
              <p class="card-description">
                Course Details
{#                <code>.table</code>#}
              </p>
              <div class="table-responsive">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Course Name</th>
                      <th>Overall Marks</th>
                      <th>Average Marks</th>
                      <th>Course Rank</th>
                    </tr>
                  </thead>
                  <tbody>
                {% for student in course_table %}
                    <tr>
                      <td>{{  student.0 }}</td>
                      <td>{{ student.1 }}</td>
                        <td><label class="badge badge-warning">{{ student.2 }}</label></td>
                      <td>
                        <label>{{ student.3 }}</label>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <div class="col-lg-6 grid-margin stretch-card">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">This Course</h4>
              <p class="card-description">
               {{ course }}
{#                <code>.table-hover</code>#}
              </p>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>Exam Name</th>
                        <th>Marks Obtained</th>
                      <th>Average Marks</th>
                      <th>Top Marks</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for quiz in this_course %}
                    <tr>
                      <td>{{ quiz.0 }}</td>
                        <td>{{  quiz.3 }}</td>

                      <td>{{  quiz.1 }}</td>
                      <td class="text-danger">{{ quiz.2 }}
                        <i class="mdi mdi-arrow-down"></i>
                      </td>

                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}