ase1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from registration import views as jk
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('dashboard/', include(('dashboard.urls', 'dashboard'))),
                  path('registration/', include('registration.urls')),
                  path('', include(('landing_page.urls', 'landing_page'))),
                  path('student_report/', include(('student_report.urls','student_report'))),
                  url(r'auth/', include(('social_django.urls', 'social'))),
                  path('api/<str:course_id>',jk.courselogdetail,name='api')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
from registration import views as p

app_name = "dashboard"

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path('needy_list/', views.needy_list, name='needy_list'),
    path('list_of_students/', views.list_of_students, name='list_of_students'),
    path('editprofile/', p.editprofile, name='editprofile'),
    path('custom_404/', views.custom_404, name='custom_404'),
    path('graph', views.graph, name='graph'),
]

registration/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views
import social_django
app_name = "registration"

urlpatterns = [
    path('login/', views.login_display, name='login'),
    path('register/', views.register_display, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('login/reset_password/', views.reset_password, name='reset'),
    url(r'display_reset_password/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.display_reset_password, name='display_reset_password'),
    path('course/', views.course_selection, name='course_selection'),
    url(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.activate, name='activate'),
    path('save_password/',views.save_password,name='save_password'),
    path('edit_profile/',views.editprofile,name='edit_profile'),
    path('all_profiles/',views.allprofiles,name='allprofiles'),
    path('professor/',views.professor,name='professor')
    ]

student_report/urls.py
from django.urls import path
from . import views

app_name = 'student_report'

urlpatterns = [
    path('<int:id>/', views.student_report, name="student_report"),
    path('charts/<int:id>/', views.charts, name="charts"),
    path('tables/<int:id>/', views.tables, name="tables"),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Enrollments(models.Model):
    course_id = models.CharField(max_length=15)
    student_id = models.CharField(max_length=15)
    student_name = models.CharField(max_length=60)
    prof_id = models.CharField(max_length=15)
    status = models.CharField(max_length=20)
    performance = models.CharField(max_length=20,default='-')
    persistance = models.CharField(max_length=20,default='-')
    label = models.CharField(max_length=90,default='-')


    def __str__(self):
        return self.student_name

class csvfile(models.Model):
    req_file = models.FileField(upload_to='media_')

class Marks(models.Model):
    student_name = models.CharField(max_length=15)
    student_id = models.CharField(default=0,max_length=15)
    course_id = models.CharField(default=0,max_length=15)
    prof_id = models.CharField(default=0,max_length=15)
    marks = models.FloatField(default=0)
    q_name = models.CharField(max_length=50)

    class Meta:
        unique_together = ('student_id', 'course_id','prof_id','q_name','student_name')

class student_ranks(models.Model):
    student_id = models.CharField(max_length=15)
    course = models.CharField(max_length=50,default='-')
    class_rank = models.IntegerField(default=0)
    exam_rank = models.IntegerField(default=0)
    lab_rank = models.IntegerField(default=0)
    asgn_rank = models.IntegerField(default=0)
    oth_rank = models.IntegerField(default=0)
    best_marks = models.IntegerField(default=0)
    worst_marks = models.IntegerField(default=0)
    best_exam  = models.CharField(max_length=50,default='-')
    worst_exam = models.CharField(max_length=50, default='-')
    overall  = models.IntegerField(default=0)

class course_dashboard(models.Model):
    professor = models.OneToOneField(User,on_delete=models.CASCADE)
    course = models.CharField(max_length=50,default='-')
    course_difficulty = models.CharField(max_length=15,default='-')
    course_risk = models.CharField(max_length=15,default='-')
    course_average = models.CharField(max_length=15,default='-')
    exam_difficulty = models.CharField(max_length=15,default='-')
    exam_cheat_risk = models.CharField(max_length=15,default='-')
    exam_average = models.CharField(max_length=15,default='-')
    quartile_1 = models.FloatField(default=0)
    quartile_2 = models.FloatField(default=0)
    quartile_3 = models.FloatField(default=0)
    course_student_list = models.CharField(max_length=150,default='-')
    exam_student_list = models.CharField(max_length=150,default='-')
    needy_student_list = models.CharField(max_length=150,default='-')

class course_exams(models.Model):
    course_id = models.CharField(max_length=150,default='-')
    quiz_name = models.CharField(max_length=150,default='-')
    max_marks = models.IntegerField(default=0)
    avg_marks = models.CharField(max_length=50,default=0)

dashboard/forms.py
from django import forms
from .models import csvfile


class file_class(forms.ModelForm):
    req_file = forms.FileField(widget=forms.FileInput(attrs={'id': 'file-input', 'class': 'image-upload'}))

    class Meta:
        model = csvfile
        fields = ('req_file',)

dashboard/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from registration.models import professor_profile
from .models import Marks
from .models import Enrollments, course_dashboard, student_ranks, course_exams
from django.http import HttpResponse
from django.core.paginator import Paginator
from .forms import file_class
from django.shortcuts import render
import dashboard.algo as alg
from django.contrib.auth.decorators import login_required


# import pdfkit
def add_to_database(pat, username, course_id):
    path = 'media/media_/' + pat
    co_id = course_id
    pr_id = username

    Marks.objects.filter(course_id=co_id).delete()
    Enrollments.objects.filter(course_id=co_id).delete()

    with open(path) as f:
        f1 = f.readline().split(",")
        f1[len(f1) - 1] = f1[len(f1) - 1].rstrip()

        take = return_firstline_as_tuple(f1)

        f.seek(0, 0)
        f_all = f.readlines()

        tuples = return_tuple(f_all)
        headers = [i for i in take]
        # print(list(tuples))
        # #headers = ['RollNumber', 'Name', 'exam-mid-35', 'exam-end-50', 'lab-basic01-20', 'lab-basic02-20',
        #            'lab-basic03-20', 'asgn-basic01-15', 'asgn-basic02-15', 'asgn-basic03-15', 'asgn-basic04-15',
        #            'oth-quiz01-30', 'oth-quiz02-30', 'oth-quiz03-30']
        # global df
        df = alg.initialse(tuples, headers)
        NeedyList = alg.mainFunc(df)
        CourseOverview = alg.CourseStats(df)
        ExamOverview = alg.ExamStats(df)
        Persistent_Labels = alg.PersistentLabels(df)
        Performance_Labels = alg.PerformanceLabels(df)
        student_report_details = alg.getRankMatrix(df)
        student_marks = alg.studentMarks(df)

        overall_marks = alg.OverallMarks(df)
        exam_marks = alg.ExamDetails(df)
        box_marks = alg.BoxPlot(df)
        print(box_marks)

        for i in range(len(exam_marks)):
            if len(course_exams.objects.filter(course_id=course_id, quiz_name=exam_marks[i][0])) <= 0:
                course_exams.objects.create(course_id=course_id, quiz_name=exam_marks[i][0], avg_marks=exam_marks[i][1],
                                            max_marks=exam_marks[i][2])
            else:
                p = course_exams.objects.get(course_id=course_id, quiz_name=exam_marks[i][0])
                p.quiz_name = exam_marks[i][0]
                p.avg_marks = exam_marks[i][1]
                p.max_marks = exam_marks[i][2]
                p.save()
        for i in range(len(student_report_details)):
            if len(student_ranks.objects.filter(student_id=student_report_details[i][0], course=co_id)) <= 0:
                student_ranks.objects.create(student_id=student_report_details[i][0],
                                             class_rank=student_report_details[i][1],
                                             exam_rank=student_report_details[i][2],
                                             lab_rank=student_report_details[i][3],
                                             asgn_rank=student_report_details[i][4]
                                             , oth_rank=student_report_details[i][5],
                                             course=co_id)
            else:
                p = student_ranks.objects.get(student_id=student_report_details[i][0], course=co_id)
                p.class_rank = student_report_details[i][1]
                p.exam_rank = student_report_details[i][2]
                p.lab_rank = student_report_details[i][3]
                p.asgn_rank = student_report_details[i][4]
                p.oth_rank = student_report_details[i][5]
                p.save()
        for i in range(len(student_marks)):
            p = student_marks[i][0]
            student = student_ranks.objects.get(student_id=p, course=co_id)
            student.best_marks = student_marks[i][1]
            student.worst_marks = student_marks[i][2]
            student.best_exam = student_marks[i][3]
            student.worst_exam = student_marks[i][4]
            student.save()

        # print(overall_marks)
        # print("Persistence label : ",Persistent_Labels)
        f_all[len(f_all) - 1] = f_all[len(f_all) - 1] + '\n'
        for i in range(1, len(f_all)):
            f_all[i] = f_all[i].rstrip()
            pr = student_ranks.objects.get(student_id=f_all[i][0], course=co_id)
            pr.overall = int(overall_marks[i - 1])
            # print('pr-',pr.overall)

            pr.save()
            if f_all[i] != '':
                f2 = f_all[i].split(',')
                # print(f2)
                if str(f2[0]) in Persistent_Labels[0]:
                    per_value = 'Consistent'
                elif str(f2[0]) in Persistent_Labels[1]:
                    per_value = 'Moderately Varying'
                else:
                    per_value = 'Highly Varying'

                if str(f2[0]) in Performance_Labels[0]:
                    performance_value = 'Exceptional'
                elif str(f2[0]) in Performance_Labels[1]:
                    performance_value = 'Promising'
                elif str(f2[0]) in Performance_Labels[2]:
                    performance_value = 'Average'
                else:
                    performance_value = 'Needy'

                Enrollments.objects.create(course_id=co_id, student_id=f2[0], student_name=f2[1], prof_id=pr_id,
                                           status="not_needy", persistance=per_value, performance=performance_value)
                for j in range(0, len(f2) - 2):
                    marks = f2[j + 2]
                    qname = f1[j + 2]

                    Marks.objects.create(student_name=f2[1], student_id=f2[0], marks=f2[j + 2], q_name=f1[j + 2],
                                         course_id=co_id,
                                         prof_id=pr_id)

    # all_quiz_marks_in_a_course()
    # all_quiz_marks_in_all_courses()
    return [CourseOverview, ExamOverview, NeedyList, box_marks]


#
# def call():
#     print(Marks.objects.filter(q_name="q3"))

#
# def return_tuple(line):
#     req_tuple = ()
#     for n in range(1, len(line)):
#         line[n] = line[n].rstrip()
#         x = tuple(line[n].split(','))
#         req_tuple += (x,)
#     print(req_tuple)

# tup=tuple(a)
# print(tup(0))

# a[0]=tuple(a[0])
# print(type(a[0]))

# tup=tuple(a)
#
# print(tup(0))

# @login_required()
def dashboard(request):
    form1 = file_class(request.POST, request.FILES or None)
    if request.method == 'POST':
        if form1.is_valid():
            form1.save()
            # print(request.FILES['req_file'])
            user = User.objects.get(username=request.user)
            profile = professor_profile.objects.get(professor=user)
            file1 = str(request.FILES['req_file'])
            dashboard_stats = add_to_database(file1, user.username, profile.professor_course)
            p = course_dashboard.objects.get(professor=user)
            p.course = profile.professor_course
            p.course_difficulty = dashboard_stats[0][0]
            p.course_risk = dashboard_stats[0][1]
            p.course_average = dashboard_stats[0][3]
            p.exam_difficulty = dashboard_stats[1][0]
            p.exam_cheat_risk = dashboard_stats[1][1]
            p.exam_average = dashboard_stats[1][3]
            p.quartile_1 = dashboard_stats[0][4][0]
            p.quartile_2 = dashboard_stats[0][4][1]
            p.quartile_3 = dashboard_stats[0][4][2]
            value = ''
            for j, i in enumerate(dashboard_stats[0][2]):
                if j == 0:
                    value = value + str(i)
                else:
                    value = value + '-' + str(i)
            p.course_student_list = value
            value = ''
            for j, i in enumerate(dashboard_stats[1][2]):
                if j == 0:
                    value = value + str(i)
                else:
                    value = value + '-' + str(i)
            p.exam_student_list = value
            value = ''
            for j, i in enumerate(dashboard_stats[2]):
                if j == 0:
                    value = value + str(i)
                else:
                    value = value + '-' + str(i)
            p.needy_student_list = value
            p.save()

            dashboard_marks = {'exam_marks': 0, 'lab_marks': 0, 'asgn_marks': 0, 'oth_mark': 0}
            total_marks = Marks.objects.filter(prof_id=user, course_id=profile.professor_course).all()

            marks = [i.marks for i in total_marks if i.q_name[:4] == 'exam']
            dashboard_marks['exam_marks'] = marks

            marks = [i.marks for i in total_marks if i.q_name[:3] == 'lab']
            dashboard_marks['lab_marks'] = marks

            marks = [i.marks for i in total_marks if i.q_name[:4] == 'asgn']
            dashboard_marks['asgn_marks'] = marks

            marks = [i.marks for i in total_marks if i.q_name[:3] == 'oth']
            dashboard_marks['oth_marks'] = marks

            course_risk_list = []

            for i in dashboard_stats[0][2]:
                if i != '':
                    q = Enrollments.objects.get(prof_id=user, course_id=profile.professor_course, student_id=i)
                    course_risk_list.append([q.student_name, i, q.performance, q.persistance])
            exam_risk_list = []
            for i in dashboard_stats[1][2]:
                if i != '':
                    q = Enrollments.objects.get(prof_id=user, course_id=profile.professor_course, student_id=i)
                    course_risk_list.append([q.student_name, i, q.performance, q.persistance])

            context = {'form': form1, 'courseoverview': dashboard_stats[0], 'examoverview': dashboard_stats[1],
                       'needystudents': dashboard_stats[2], 'username': user.username, 'photo': profile.professor_photo,
                       'dashboard_marks'
                       : dashboard_marks, 'course_risk_list': course_risk_list,

dashboard/templates/dashboard/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    {% block head %}
    {% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="shortcut icon" type="image/png" href="{% static "landing_page/images/LMS-i.png" %}"/>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static "dashboard/css/style.css" %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/design.css' %}">
    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
            integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
            crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
            integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
            crossorigin="anonymous"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

</head>

<body class="dashboard-body">
{% if user.is_authenticated %}
    <div class="wrapper">
        <nav id="sidebar">

            <ul class="list-unstyled components">
                <li>
                    <a href="#">
                    </a>
                </li>
                <li>
                    <a href="#">
                    </a>
                </li>

                <li class="dashboard-nav-link">
                    <a href="{% url 'registration:professor' %}">
                        <img class="img-responsive rounded-circle mx-5 mt-3 border border-primary" src="{{ photo.url }}"
                             alt="Professor Name" width="120" height="120"/>
                        <div class="page-header mx-4 my-4 text-center">
                            <h1>Hi, <br/>{{ username }}!</h1>
                        </div>
                    </a>
                </li>
                <hr/>
                <li class=sidebar-navass="dashboard-nav-link">
                    <a href="{% url 'dashboard:dashboard' %}">
                        <i class="fas fa-graduation-cap fa-2x mr-2" data-target="classOverview"></i>
                        <span class="font-weight-bold">Class Overview</span>
                    </a>
                </li>

                <li class=sidebar-navass="dashboard-nav-link">
                    <a href="{% url 'dashboard:needy_list' %}">
                        <i class="fas fa-asterisk fa-2x mr-2" data-target="needyList"></i>
                        <span class="font-weight-bold">Needy List</span>
                    </a>
                </li>

                <li class="sidebar-nav">
                    <a href="{% url 'dashboard:list_of_students' %}" data-target="listStudents">
                        <i class="fas fa-list-alt fa-2x mr-2"></i>
                        <span class="font-weight-bold">List of All Students</span>
                    </a>
                </li>

                <li class="sidebar-nav">
                    <a href="{% url 'dashboard:graph' %}" data-target="graph">
                        <i class="fas fa-chart-bar fa-2x mr-2"></i>
                        <span class="font-weight-bold">Visualisations</span>
                    </a>
                </li>
            </ul>


        </nav>

        <!-- Page Content  -->
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'landing_page:landing_page' %}">
                        <img class="img-responsive" src="{% static "landing_page/images/LMS.svg" %}" alt="LMS"
                             width="50"
                             height="50" style="position:absolute;z-index:4;top:7%;left:6%;">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link text-light font-weight-bold"
                                   href="{% url 'landing_page:landing_page' %}">HOME</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light font-weight-bold" href="{% url 'dashboard:dashboard' %}">DASHBOARD</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-light font-weight-bold" href="{% url 'registration:logout' %}">LOGOUT</a>
                            </li>

                        </ul>


                    </div>
                </div>
            </nav>

            <button type="button" id="sidebarCollapse" class="btn">
                <i class="fas fa-align-left"></i>
            </button>
            {% block content %}
                <div id="container">
                </div>
            {% endblock %}
        </div>

    </div>

    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white small mb-2 footer_text">Copyright &copy; LMS</p>
            <p class="m-0 text-center text-white small footer_text">Made With <i class="fa fa-heart mx-1"></i>work</p>
        </div>

        <a class="scrollup" style="display: none;">Scroll</a>
        <!-- /.container -->
    </footer>


    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            // Set trigger and container variables
            var trigger = $('#sidebar ul li a'),
                container = $('#content');

            // Fire on click
            trigger.on('click', function () {
                // Set $this for re-use. Set target from data attribute
                var $this = $(this),
                    target = $this.data('target');

                // Load target page into container
                container.load(target + '.php');

                // Stop normal link behavior
                return false;
            });
        });
    </script>


    {% block script %}
    {% endblock %}




{% endif %}


</body>
</html>

dashboard/templates/dashboard/graph.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block head %}
    <title>LMS</title>

{% endblock %}

{% block content %}
    <form method="POST" accept-charset="utf-8" class="mt-4">{% csrf_token %}
        <select name="quizid">
            {% for quiz in quizzes %}
                <option value="{{ quiz }}">{{ quiz }}</option>
            {% endfor %}
        </select>
        <button type="submit">Submit</button>
    </form>
    <div class="text-center mt-3">
        <p class="display-4">Choose An Exam here</p>
        <img src="{% static 'dashboard/images/34.jpg' %}" class="rounded-circle mt-2" alt="GRAPHS">
    </div>


{% endblock %}


{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <script>
        var ctx = document.getElementById("myChart").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ["Test1", "Test2", "Test3", "Test4", "Test5", "Test6", "Test7",],
                datasets: [{
                    label: '',
                    data: [12, 19, 3, 17, 28, 24, 7],
                    backgroundColor: "rgba(153,255,51,0.9)"
                }, {
                    label: '',
                    data: [30, 29, 5, 5, 20, 3, 10],
                    backgroundColor: "rgba(255,153,0,0.9)"
                }, {
                    label: '',
                    data: [45, 65, 15, 85, 20, 35, 75],
                    backgroundColor: "rgba(221,123,24,0.9)"
                }, {
                    label: '',
                    data: [60, 85, 56, 57, 25, 71, 30],
                    backgroundColor: "rgba(153,240,0,0.9)"
                }]
            }
        });
    </script>

{% endblock %}

dashboard/templates/dashboard/list_of_students.html
{% extends 'dashboard/base.html' %}
{% load static %}

{% block head %}
    <title>Needy_List</title>
    <link rel="stylesheet" href="{% static "dashboard/css/needyStyle.css" %}">
{% endblock %}

{% block content %}
    <div id="students">
        <input class="search" placeholder="Search"/>
        <button class="sort" data-sort="name">
            Sort by name
        </button>
<br><br>

        <ul class="list">
            {% for student in allstudents %}

                <li>
                    <div class="row">
                        <div class="col-2">
                            <img class="rounded-circle mx-3" src="{% static 'dashboard/images/st6.jpg' %}"
                                 alt="Person"
                                 width="96"
                                 height="96">
                        </div>

                        <div class="col-10">
                            <a href="{% url 'student_report:student_report' student.0 %}">
                                <div class="row chip my-2" style="width:100%;">
                                    <div class="row">
                                        <div class="col-3 mr-0">
                                            <span class="name pt-2 pl-3 font-weight-bold" style="font-family: 'Montserrat', sans-serif;">{{ student.1 }}</span>
                                        </div>

                                        <div class="col-3 pt-2">
                                            <span class="text-secondary"><h6>Roll No - {{ student.0 }}</h6></span>
                                        </div>

                                        <div class="col-6 pt-2">
                                            <span class="text-right badge badge-primary ml-5 mr-2"><h6>{{ student.2 }}</h6></span>
                                            <span class="text-right badge badge-warning mx-2"><h6>{{ student.3 }}</h6></span>
                                            {% if student.4 != '-' %}
                                            <span class="text-right badge badge-success mx-2"><h6>{{ student.4 }}</h6></span>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <hr/>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="pagination justify-content-center">
        {% if allstudents.has_previous %}
            <a class="pagination-action" href="?page=1">
                <i class="fa fa-angle-double-left" aria-hidden="true"></i>
            </a>
            <a class="pagination-action" href="?page={{ allstudents.previous_page_number }}">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
            </a>
        {% endif %}

        {% for num in allstudents.paginator.page_range %}

            {% if allstudents.number == num %}
                <span class="pagination-number pagination-current mx-2">{{ num }}</span>
            {% elif num > allstudents.number|add:'-3' and num < allstudents.number|add:'3' %}
                <a class="pagination-number mx-2" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if allstudents.has_next %}
            <a class="pagination-action" href="?page={{ allstudents.next_page_number }}">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
            </a>
            <a class="pagination-action" href="?page={{ allstudents.paginator.num_pages }}">
                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
            </a>
        {% endif %}

    </div>

{% endblock %}

{% block script %}
    <script src="{% static "dashboard/js/list.min.js" %}"></script>
    <script>
        var options = {
            valueNames: ['name']
        };

        var userList = new List('students', options);
    </script>
{% endblock %}

dashboard/templates/dashboard/needy_list.html
{% extends 'dashboard/base.html' %}

{% block head %}
    <title>Needy_List</title>
{% endblock %}

{% block content %}


    <div class="row justify-content-center">
        {% for student in needyList %}
            <div class="col-xs-12 col-md-6 col-lg-4 mx-auto">
                <div class="card d-inline-block my-5">
                    <a href="{% url 'student_report:student_report' student.1 %}" class="needy-card">
                        <img class="card-img-top" src="http://placehold.it/250x150" alt="Card image cap">
                        <div class="card-block p-2">
                            <h4 class="card-title">{{ student.0 }}</h4>
                            <p class="card-text">Roll No - {{ student.1 }}</p>
                            <span class="badge badge-primary">{{ student.2 }}</span>
                            <span class="badge badge-success">{{ student.3 }}</span>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}


{% block script %}
    <script>
        $(document).ready(function () {
            // executes when HTML-Document is loaded and DOM is ready
            console.log("document is ready");


            $(".card").hover(
                function () {
                    $(this).addClass('shadow-lg').css('cursor', 'pointer');
                }, function () {
                    $(this).removeClass('shadow-lg');
                }
            );

// document ready
        });

    </script>
{% endblock %}